inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/*'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
