AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/*'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/DotPosition:
  EnforcedStyle: trailing

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/modules/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/modules/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
