version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - PORT=3000
      - POSTGRES_URL=postgres://postgres:example@postgres:5432/emissions_scenario_portal
      - REDIS_URL=redis://redis:6379
      - RAILS_SERVE_STATIC_FILES=true
    restart: always
    container_name: emissions-scenario-portal
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=emissions_scenario_portal

  redis:
    image: redis:3.2.5
    ports:
      - "6379"
