apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: climate-watch
  name: emissions-scenario-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: emissions-scenario-portal
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
