apiVersion: v1
kind: Service
metadata:
  namespace: climate-watch
  labels:
    name: emissions-scenario-portal
  name: emissions-scenario-portal
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: emissions-scenario-portal
